[net]
git-fetch-with-cli=true

[profile.dev]
opt-level = 1
lto = false
codegen-units = 12

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
linker="clang"
rustflags=["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
